const THREEKIT_FETCH_MODELS = "THREEKIT_FETCH_MODELS";
const THREEKIT_SET_MODELS_SET = "THREEKIT_SET_MODELS_SET";
const THREEKIT_SELECT_MODEL = "THREEKIT_SELECT_MODEL";
const THREEKIT_FETCH_TEXTURES = "THREEKIT_FETCH_TEXTURES";
const THREEKIT_SET_TEXTURES_SET = "THREEKIT_SET_TEXTURES_SET";
const THREEKIT_FETCH_NAILHEAD_MATERIALS = "THREEKIT_FETCH_NAILHEAD_MATERIALS";
const THREEKIT_SET_NAILHEAD_MATERIALS_SET = "THREEKIT_SET_NAILHEAD_MATERIALS_SET";
const THREEKIT_SET_SELECTED_MODEL_SEATING_TEXTURE = "THREEKIT_SET_SELECTED_MODEL_SEATING_TEXTURE";
const THREEKIT_SET_SELECTED_MODEL_NAILHEADS_MATERIAL = "THREEKIT_SET_SELECTED_MODEL_NAILHEADS_MATERIAL";
const THREEKIT_SET_COLOR_BLOCKING_TEXTURES = "THREEKIT_SET_COLOR_BLOCKING_TEXTURES";
const THREEKIT_INIT_CAMERA_VALUES = "THREEKIT_INIT_CAMERA_VALUES";
const THREEKIT_SET_ACTIVE_CAMERA = "THREEKIT_SET_ACTIVE_CAMERA";
const THREEKIT_SET_SINGLE_PLAYER_LOADING_STATUS = "THREEKIT_SET_SINGLE_PLAYER_LOADING_STATUS";
const THREEKIT_SET_ROOM_BUILDER_PLAYER_LOADING_STATUS = "THREEKIT_SET_ROOM_BUILDER_PLAYER_LOADING_STATUS";
const THREEKIT_SET_ROOM_BUILDER_COMPONENT_MODEL = "THREEKIT_SET_ROOM_BUILDER_COMPONENT_MODEL";

export default {
  THREEKIT_FETCH_MODELS,
  THREEKIT_SET_MODELS_SET,
  THREEKIT_SELECT_MODEL,
  THREEKIT_FETCH_TEXTURES,
  THREEKIT_SET_TEXTURES_SET,
  THREEKIT_SET_SELECTED_MODEL_SEATING_TEXTURE,
  THREEKIT_FETCH_NAILHEAD_MATERIALS,
  THREEKIT_SET_NAILHEAD_MATERIALS_SET,
  THREEKIT_SET_SELECTED_MODEL_NAILHEADS_MATERIAL,
  THREEKIT_SET_COLOR_BLOCKING_TEXTURES,
  THREEKIT_INIT_CAMERA_VALUES,
  THREEKIT_SET_ACTIVE_CAMERA,
  THREEKIT_SET_SINGLE_PLAYER_LOADING_STATUS,
  THREEKIT_SET_ROOM_BUILDER_PLAYER_LOADING_STATUS,
  THREEKIT_SET_ROOM_BUILDER_COMPONENT_MODEL,
};
